name: 自動部署 GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 取得程式碼
        uses: actions/checkout@v3

      - name: 設定 GitHub Pages
        uses: actions/configure-pages@v3

      - name: 上傳靜態檔案
        uses: actions/upload-pages-artifact@v2
        with:
          path: './'   # 你的網站靜態檔案根目錄，有 index.html

      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v2
